# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 750

format = """
[](#5e81ac)\
[$os$username](bg:#5e81ac fg:#2e3440)$hostname\
[](bg:#81a1c1 fg:#5e81ac)\
$directory\
[](bg:#88c0d0 fg:#81a1c1)\
$git_branch$git_commit$git_state$git_metrics$git_status\
[](bg:#8fbcbb fg:#88c0d0)\
[$package$golang$helm$nodejs$terraform](bg:#8fbcbb fg:#88c0d0 bold)\
[](bg:#d9dee9 fg:#8fbcbb)\
$cmd_duration\
[](fg:#d9dee9)\
$line_break\
$character
"""

# EXCLUDED $
# ==========
# to add later if I need them lmao
# localip, shlvl, singularity, kubernetes
# vcsh, fossil_branch, fossil_branch_metrics, hg_branch, pijul_channel, docker_context
# buf, nix_shell, conda, meson, spack
# memory_usage
# aws, gcloud, openstack, azure
# direnv, env_var, crytal, custom, sudo
# jobs, status, container, shell

# GIT
# ===

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = '󰘬 '
style = 'fg:#2e3440 bg:#88c0d0'

[git_commit]
format='[\($hash$tag\) ]($style)'
style = 'fg:#2e3440 bg:#88c0d0'

[git_state]
style = 'fg:#2e3440 bg:#88c0d0'

[git_metrics]

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
style = "fg:#2e3440 bg:#88c0d0"

# LANGUAGES
# =========

[lua]
symbol = ' '
style = 'inherit'
format = '[$symbol$version]($style) '
[python]
symbol = ' '
style = 'inherit'
format = '[$symbol$version]($style) '
[golang]
symbol = '󰟓 '
style = 'inherit'
format = '[$symbol$version]($style) '
[helm]
symbol = '󱃾'
style = 'inherit'
format = '[$symbol$version]($style) '
[terraform]
symbol = ' '
style = 'inherit'
format = '[$symbol$version]($style) '
[nodejs]
symbol = '󰎙 '
style = 'inherit'
format = '[$symbol$version]($style) '

# MISC
# ====

[username]
show_always = true
style_root = 'bg:#5e81ac bold fg:#bf616a'
format = '[$user ]($style)'
style_user = 'fg:#2e3440 bg:#5e81ac'

[hostname]
ssh_only = true
style = 'fg:#2e3440 bg:#5e81ac'
format = '[@ $ssh_symbol$hostname ]($style)'
ssh_symbol = ' '

[os]
style = 'fg:#2e3440 bg:#5e81ac'
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[shell]
disabled = false

[directory]
style = 'fg:#2e3440 bg:#81a1c1'
home_symbol='󰋜 '
read_only = ' '
format = '[ 󰉋 $path ]($style)[$read_only]($read_only_style)'
read_only_style = 'fg:#2e3440 bold bg:#81a1c1'

[sudo]
disabled = false
symbol = ' '
style = 'fg:#2e3440 bg:#d9dee9'
format = '[ $symbol]($style)'

[cmd_duration]
format = '[ 󰔚 $duration ]($style)'
style = 'fg:#2e3440 bg:#d9dee9'

[character]
success_symbol = '[ 󱞩](bold green)'
error_symbol = '[ 󱞩](bold red)'
vimcmd_symbol = '[  󱞩](bold green)'
